/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as ServicosRouteImport } from './routes/servicos'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as AnamneseRouteImport } from './routes/anamnese'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminConfiguracoesRouteImport } from './routes/admin.configuracoes'
import { Route as AdminClientesRouteImport } from './routes/admin.clientes'
import { Route as AdminAgendaRouteImport } from './routes/admin.agenda'

const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicosRoute = ServicosRouteImport.update({
  id: '/servicos',
  path: '/servicos',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const AnamneseRoute = AnamneseRouteImport.update({
  id: '/anamnese',
  path: '/anamnese',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminConfiguracoesRoute = AdminConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminClientesRoute = AdminClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAgendaRoute = AdminAgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/anamnese': typeof AnamneseRoute
  '/contato': typeof ContatoRoute
  '/servicos': typeof ServicosRoute
  '/sobre': typeof SobreRoute
  '/admin/agenda': typeof AdminAgendaRoute
  '/admin/clientes': typeof AdminClientesRoute
  '/admin/configuracoes': typeof AdminConfiguracoesRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/anamnese': typeof AnamneseRoute
  '/contato': typeof ContatoRoute
  '/servicos': typeof ServicosRoute
  '/sobre': typeof SobreRoute
  '/admin/agenda': typeof AdminAgendaRoute
  '/admin/clientes': typeof AdminClientesRoute
  '/admin/configuracoes': typeof AdminConfiguracoesRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/anamnese': typeof AnamneseRoute
  '/contato': typeof ContatoRoute
  '/servicos': typeof ServicosRoute
  '/sobre': typeof SobreRoute
  '/admin/agenda': typeof AdminAgendaRoute
  '/admin/clientes': typeof AdminClientesRoute
  '/admin/configuracoes': typeof AdminConfiguracoesRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/anamnese'
    | '/contato'
    | '/servicos'
    | '/sobre'
    | '/admin/agenda'
    | '/admin/clientes'
    | '/admin/configuracoes'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/anamnese'
    | '/contato'
    | '/servicos'
    | '/sobre'
    | '/admin/agenda'
    | '/admin/clientes'
    | '/admin/configuracoes'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/anamnese'
    | '/contato'
    | '/servicos'
    | '/sobre'
    | '/admin/agenda'
    | '/admin/clientes'
    | '/admin/configuracoes'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AnamneseRoute: typeof AnamneseRoute
  ContatoRoute: typeof ContatoRoute
  ServicosRoute: typeof ServicosRoute
  SobreRoute: typeof SobreRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicos': {
      id: '/servicos'
      path: '/servicos'
      fullPath: '/servicos'
      preLoaderRoute: typeof ServicosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/anamnese': {
      id: '/anamnese'
      path: '/anamnese'
      fullPath: '/anamnese'
      preLoaderRoute: typeof AnamneseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/configuracoes': {
      id: '/admin/configuracoes'
      path: '/configuracoes'
      fullPath: '/admin/configuracoes'
      preLoaderRoute: typeof AdminConfiguracoesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/clientes': {
      id: '/admin/clientes'
      path: '/clientes'
      fullPath: '/admin/clientes'
      preLoaderRoute: typeof AdminClientesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/agenda': {
      id: '/admin/agenda'
      path: '/agenda'
      fullPath: '/admin/agenda'
      preLoaderRoute: typeof AdminAgendaRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAgendaRoute: typeof AdminAgendaRoute
  AdminClientesRoute: typeof AdminClientesRoute
  AdminConfiguracoesRoute: typeof AdminConfiguracoesRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAgendaRoute: AdminAgendaRoute,
  AdminClientesRoute: AdminClientesRoute,
  AdminConfiguracoesRoute: AdminConfiguracoesRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AnamneseRoute: AnamneseRoute,
  ContatoRoute: ContatoRoute,
  ServicosRoute: ServicosRoute,
  SobreRoute: SobreRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
